### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [nickbild/vectron_65#1]
Hello!

I found link to this project from https://hackaday.com/2020/11/16/vectron-adds-basic-and-christmas-tree-control/

Could you please add information about license of this repository — is it allowed to copy, change and use code in any purpose?
It would be great to see any popular open source license.

**Comment by nickbild** [comment]
I added an MIT license to the repo.  Have fun!

**Comment by vazhnov** [comment]
@nickbild , great, thank you!
